version: '2.1'

networks:
  servers:

services:

  balancer:
    build: .
    command: "lb"
    networks:
      - servers
    ports:
      - "8090:8090"

  server1:
    build: .
    networks:
      - servers
    ports:
      - "8080:8080"

  server2:
    build: .
    networks:
      - servers
    ports:
      - "8081:8080"

  server3:
    build: .
    networks:
      - servers
    ports:
      - "8082:8080"

  client1:
    build: .
    command: "client --target http://balancer:8090"
    networks:
      - servers

  client2:
    build: .
    command: "client --target http://balancer:8090"
    networks:
      - servers

  client3:
    build: .
    command: "client --target http://balancer:8090"
    networks:
      - servers