FROM golang:1.15 as build

RUN apt-get update && apt-get install -y ninja-build

RUN go get -u github.com/MaryLynJuana/KPI_Assembly_System/build/cmd/bood

WORKDIR /go/src/practice-2
COPY . .

# ENTRYPOINT ["bood", "integration-tests"]
# ENTRYPOINT ["echo", "ok"]
ENTRYPOINT ["bood", "./out/reports/integration-tests"]
